#Desafios de Nunpy - Continuação

Exercícios (continuação) de introdução ao NumPy (conceitos básicos)

1) Considere o seguinte array NumPy:

numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Sem alterar os valores armazenados:

a) Transforme numeros em um array com 3 linhas e 4 colunas.

b) Transforme o array original em um array com 4 linhas e 3 colunas.

c) Transforme-o em um array com 2 linhas e 6 colunas.

d) Use shape para mostrar as dimensões de cada array criado.

e) O que aconteceria se fosse executado numeros.reshape(5, 3)? Explique o motivo.


In [12]:
import numpy as np

numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

grid = np.arange(1, 13).reshape((3, 4))
print(f' a) Vetor transformado em matrix 3 por 4 \n{grid}')

grid2 = np.arange(1, 13).reshape((4, 3))
print(f'\n b) Vetor transformado em matrix 4 por 3 \n{grid2}')

grid3 = np.arange(1, 13).reshape((2, 6))
print(f'\n c) Vetor transformado em matrix 2 por 6 \n{grid3}')

print(f'\n d) Shape Grid 1: {grid.shape}')
print(f'\n d) Shape Grid 2: {grid2.shape}')
print(f'\n d) Shape Grid 3: {grid3.shape}')

print(f' e) Aconteceria um erro se caso tentassemos transformar esse vetor em uma matrix 5 por 3 '
'porque o número de colunas é insuficiênte para tal transformação')


 a) Vetor transformado em matrix 3 por 4 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 b) Vetor transformado em matrix 4 por 3 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 c) Vetor transformado em matrix 2 por 6 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 d) Shape Grid 1: (3, 4)

 d) Shape Grid 2: (4, 3)

 d) Shape Grid 3: (2, 6)
 Aconteceria um erro se caso tentassemos transformar esse vetor em uma matrix 5 por 3 porque o número de colunas é insuficiênte para tal transformação


2) Considere dois grupos de notas:

turma_a = np.array([7.5, 8.0, 6.5, 9.0])

turma_b = np.array([5.5, 7.0, 8.5, 6.0])

Utilizando np.concatenate():

a) Crie um novo array chamado notas contendo primeiro as notas da turma A e depois as notas da turma B.

b) Exiba o novo array.

c) Mostre a quantidade de elementos de notas utilizando size.

d) Acrescente um terceiro grupo:
turma_c = np.array([9.5, 8.0, 7.5])

Crie um único array contendo as notas das três turmas.

In [25]:
turma_a = np.array([7.5, 8.0, 6.5, 9.0])
notas = np.concatenate([turma_a, turma_b])


turma_b = np.array([5.5, 7.0, 8.5, 6.0])

print(f'a) e b) Todas as notas da turma A e B:\n {notas}\n')
print(f'c) Quantidades de elementos {notas.size}\n')

# Novo connunto de notas
turma_c = np.array([9.5, 8.0, 7.5])

notas_totais = np.concatenate([notas, turma_c])
print(f'd) Notas das turmas a, b e c:\n {notas_totais}')


a) e b) Todas as notas da turma A e B:
 [7.5 8.  6.5 9.  5.5 7.  8.5 6. ]

c) Quantidades de elementos 8

d) Notas das turmas a, b e c:
 [7.5 8.  6.5 9.  5.5 7.  8.5 6.  9.5 8.  7.5]


3) Uma empresa registrou as vendas realizadas durante 12 meses:

vendas = np.array([
120, 135, 142,

150, 147, 160,

175, 180, 172,

190, 205, 220
])

Cada valor corresponde a um mês, de janeiro a dezembro.

Utilizando np.split():

a) Divida o array em 4 arrays, cada um representando um trimestre.

b) Exiba separadamente os quatro arrays obtidos.

c) Mostre apenas os valores referentes ao terceiro trimestre.

d) Divida agora o array em 2 partes iguais, representando os dois semestres.

e) O que aconteceria ao tentar executar np.split(vendas, 5)? Explique

In [34]:
vendas = np.array([ 120, 135, 142,

150, 147, 160,

175, 180, 172,

190, 205, 220 ])

vendas_1_bimestre, vendas_2_bimestre, vendas_3_bimestre, vendas_4_bimestre = np.split(vendas, 4)

print('Resposta das perguntas a e b')
print(f'Vendas 1º bimestre: {vendas_1_bimestre}')
print(f'Vendas 2º bimestre: {vendas_2_bimestre}')
print(f'Vendas 3º bimestre: {vendas_3_bimestre}')
print(f'Vendas 4º bimestre: {vendas_4_bimestre}\n')

print(f'c) Vendas do 3º bimentre: {vendas_3_bimestre}\n')

# Correção para dividir em 2 partes iguais (semestres)
semestre_1, semestre_2 = np.split(vendas, 2)
print("d) Vendas por semestres (dividido igualmente)")
print(f'Vendas do 1º semestre: {semestre_1}')
print(f'Vendas do 2º semestre: {semestre_2}\n')

print("e) Aconteceria um erro, pois o nº de elementos do array de vendas (12) não é divisível por 5 para uma divisão em 5 partes iguais.")

Resposta das perguntas a e b
Vendas 1º bimestre: [120 135 142]
Vendas 2º bimestre: [150 147 160]
Vendas 3º bimestre: [175 180 172]
Vendas 4º bimestre: [190 205 220]

c) Vendas do 3º bimentre: [175 180 172]

d) Vendas por semestres (dividido igualmente)
Vendas do 1º semestre: [120 135 142 150 147 160]
Vendas do 2º semestre: [175 180 172 190 205 220]

e) Aconteceria um erro, pois o nº de elementos do array de vendas (12) não é divisível por 5 para uma divisão em 5 partes iguais.
