Importe a biblioteca NumPy utilizando o nome convencional np.

In [1]:
import numpy as np

1) Crie um array chamado notas contendo os seguintes valores:

7.5, 8.0, 6.5, 9.0, 5.5

Em seguida:

a) Exiba o array.

b) Exiba o tipo da variável notas.

c) Exiba o tipo dos elementos armazenados no array.

d) Exiba a quantidade de elementos do array

In [8]:
notas = np.array([7.5, 8.0, 6.5, 9.0, 5.5])
print(f'a: Array: {notas}')
print(f'b: Tipos da Variável: {type(notas)}')
print(f'c: Tipos dos elementos: {notas.dtype}')
print(f'd: Quantidade dos elementos: {notas.size}')

a: Array: [7.5 8.  6.5 9.  5.5]
b: Tipos da Variável: <class 'numpy.ndarray'>
c: Tipos dos elementos: float64
d: Quantidade dos elementos: 5


2) Crie o seguinte array:

idades = np.array([18, 21, 19, 23, 20, 22])

Utilizando índices e fatiamento (slicing):

a) Mostre a primeira idade.

b) Mostre a última idade.

c) Mostre as três primeiras idades.

d) Mostre os elementos das posições 2 até 4.

e) Altere a primeira idade para 19 e mostre novamente o array.


In [10]:
idade = np.array([18, 21, 19, 23, 20, 22])
print(f'a: A primeira idade {idade[0]}')
print(f'b: A última idade {idade[-1]}')
print(f'c: As três primeiras idades {idade[0:3]}')
print(f'd: Os elementos das posições 2 até 4 {idade[1:4]}')
idade[0] = 19
print(f'e: Altere a primeira idade para 19 e mostre novamente o array {idade}')

a: A primeira idade 18
b: A última idade 22
c: As três primeiras idades [18 21 19]
d: Os elementos das posições 2 até 4 [21 19 23]
e: Altere a primeira idade para 19 e mostre novamente o array [19 21 19 23 20 22]


3) Considere as temperaturas, em graus Celsius, registradas durante cinco dias:

temperaturas = np.array([20, 22, 25, 24, 21])

a) Crie um novo array contendo todas as temperaturas aumentadas em 2 graus.

b) Converta todas as temperaturas para Fahrenheit utilizando:

F = 1,8C + 32F = 1,8C + 32

c) Calcule a temperatura média.

d) Determine a maior e a menor temperatura.

In [12]:
temperaturas = np.array([20, 22, 25, 24, 21])
print(f'a: Crie um novo array contendo todas as temperaturas aumentadas em 2 graus. {temperaturas + 2}')
print(f'b: Converta todas as temperaturas para Fahrenheit utilizando: F = 1,8C + 32F = 1,8C + 32 {1.8 * temperaturas + 32}')
print(f'c: Calcule a temperatura média. {temperaturas.mean()}')
print(f'd: Determine a maior e a menor temperatura. Maior: {temperaturas.max()} Menor: {temperaturas.min()}')

a: Crie um novo array contendo todas as temperaturas aumentadas em 2 graus. [22 24 27 26 23]
b: Converta todas as temperaturas para Fahrenheit utilizando: F = 1,8C + 32F = 1,8C + 32 [68.  71.6 77.  75.2 69.8]
c: Calcule a temperatura média. 22.4
d: Determine a maior e a menor temperatura. Maior: 25 Menor: 20


4) Uma pequena loja registrou as vendas de três produtos durante quatro dias:

vendas = np.array([
[10, 12, 8, 15],
[5, 7, 9, 6],
[20, 18, 22, 25]
])

Cada linha representa um produto e cada coluna, um dia.

a) Exiba todo o array.

b) Descubra suas dimensões utilizando shape.

c) Mostre as vendas do segundo produto.

d) Mostre quantas unidades do terceiro produto foram vendidas no quarto dia.

e) Calcule o total de unidades vendidas de todos os produtos e em todos os dias.

In [15]:
vendas = np.array([ [10, 12, 8, 15], [5, 7, 9, 6], [20, 18, 22, 25] ])
print(f'a: Exiba todo o array.\n {vendas}')
print(f'b: Descubra suas dimensões utilizando shape. {vendas.shape}')
print(f'c: Mostre as vendas do segundo produto. {vendas[1]}')
print(f'd: Mostre quantas unidades do terceiro produto foram vendidas no quarto dia. {vendas[2][3]}')
print(f'e: Calcule o total de unidades vendidas de todos os produtos e em todos os dias. {vendas.sum()}')

a: Exiba todo o array.
 [[10 12  8 15]
 [ 5  7  9  6]
 [20 18 22 25]]
b: Descubra suas dimensões utilizando shape. (3, 4)
c: Mostre as vendas do segundo produto. [5 7 9 6]
d: Mostre quantas unidades do terceiro produto foram vendidas no quarto dia. 25
e: Calcule o total de unidades vendidas de todos os produtos e em todos os dias. 157
