# NumPy (1)
Exemplos retirados de **Guia do Python para Data Science**, Jake VanderPlas, 2025, Alta Books - Tradução da 2ª Edição

# Conceitos básicos sobre arrays NumPy : Atributos, Indexação e Fatiamento.

In [3]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np

In [5]:
#array de inteiros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Diferentemnte das listas em Python, arrays no NumPy só podem conter dados de um mesmo tipo. Caso seja possível, o NumPy irá converter o dado para o tipo mais abrangente (*upcast*)

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Podemos também explicitar o tipo de dados do array resultante, usando-se o parâmetro **dtype**

In [7]:
np.array ([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [8]:
#Listas aninhadas produzem arrays multidimensionais
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

As listas internas são tratadas como linhas de uma matriz

É muito mais eficiente criar arrays NumPy "do zero", ou seja, usando-se as rotinas pré-definidas, sobretudo para arrays muito grandes

In [9]:
#Cria um array de inteiros com tamanho 10 e preenchido com zeros
np.zeros (10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#Cria uma matriz 3 X 5 de valores reais (float) preenchidos com uns
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#Cria uma matriz 3 X 5 preenchido com 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Pode-se, inclusive, replicar a função *range*

In [12]:
#Cria um array preenchido por uma sequência linear, de 0 a 20, de 2 em 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#Cria um array de cinco valores regularmente espaçados entre 0 e 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Também podem-se gerar valores aleatórios

In [14]:
#Cria uma matriz 3 X 3 preenchida ccom números (pseudo)aleatórios entre 0 e 1
np.random.random((3,3))

array([[0.833605  , 0.45601001, 0.9024574 ],
       [0.38605443, 0.47249767, 0.6453354 ],
       [0.74827936, 0.7293457 , 0.9958391 ]])

In [15]:
#O mesmo que o anterior, especificando média 0 e desvio-padrão 1
np.random.normal(0, 1, (3,3))

array([[-0.3734915 , -0.57427629, -0.45807947],
       [-1.48365223,  0.43040332, -0.03010823],
       [ 0.22979313, -0.41867391, -0.50695757]])

In [16]:
#O mesmo que o anterior apenas especificando o tipo do número e seu intervalo
np.random.randint(0, 10, (3,3))

array([[1, 2, 1],
       [4, 6, 0],
       [2, 4, 3]])

In [17]:
#Cria uma matriz identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#Cria uma rray não iniciado de três valores inteiros
#Os valores serão "lixo de memória" (qualquer coisa que já estivesse lá)
np.empty(3)

array([1., 1., 1.])

# Atributos de Arrays

In [19]:
import numpy as np
seq = np.random.default_rng(seed=1298)

In [20]:
x1 = seq.integers(10, size=6)      # array unidimensional
x2 = seq.integers(10, size=(3, 4))  # array bidimensional
x3 = seq.integers(10, size=(3,4,5)) # array tridimensional

In [21]:
print ("x1: ", x1)
print ("x2: ", x2)
print ("x3: ", x3)

x1:  [7 3 3 2 5 5]
x2:  [[4 1 0 6]
 [1 7 2 8]
 [1 4 2 6]]
x3:  [[[8 7 7 5 1]
  [7 8 6 6 0]
  [2 6 2 3 6]
  [5 6 6 3 9]]

 [[9 0 2 2 3]
  [8 7 3 6 3]
  [2 5 9 5 6]
  [6 9 8 2 5]]

 [[8 7 0 1 4]
  [0 6 5 9 0]
  [8 1 4 4 7]
  [8 0 2 6 5]]]


In [22]:
print ("x3 ndim:  ", x3.ndim)
print ("x3 shape: ", x3.shape)
print ("x3 size:  ", x3.size)
print ("dtype:    ", x3.dtype)

x3 ndim:   3
x3 shape:  (3, 4, 5)
x3 size:   60
dtype:     int64


# Indexação de arrays no NumPy

In [23]:
#Análogo ao convencional (sem usar o NumPy)
x1

array([7, 3, 3, 2, 5, 5])

In [24]:
x1[0]

np.int64(7)

In [25]:
x1[-1]

np.int64(5)

In [26]:
x2[0,0]

np.int64(4)

Lembre-se: diferentemente das listas Python, os arrays NumPy possuem um tipo fixo. Assim, se tentarmos inserir um valor float em um array de inteiros, o valor será truncado automaticamente.

In [27]:
x1[0] = 3.1415926 #x1 foi criado como um array de inteiros, logo este valor será truncado
x1[0]

np.int64(3)

# Fatiamento (*slicing*)

O fatiamento (slicing) funciona igualmente às listas Python

In [28]:
# x[inicio:fim:passo]
x1[:3]  #primeiros três elementos

array([3, 3, 3])

In [29]:
x1[1::2]  # cada segundo elemento do array a partir do índice 1

array([3, 2, 5])

In [30]:
x2

array([[4, 1, 0, 6],
       [1, 7, 2, 8],
       [1, 4, 2, 6]])

In [31]:
x2[:2,:3] #primeiras duas linhas e três colunas

array([[4, 1, 0],
       [1, 7, 2]])

In [32]:
x2[::-1,::-1]  #todas as linhas e colunas, em ordem inversa

array([[6, 2, 4, 1],
       [8, 2, 7, 1],
       [6, 0, 1, 4]])

Diferentemente do fatiamento do Python básico, o fatiamento de arrays NumPy retorna como ***view***

Uma ***view*** é uma referência direta ao elemento original e não uma cópia!
Alterações realizadas no subarray
**terão efeito** no array original.

In [33]:
print(x2)

[[4 1 0 6]
 [1 7 2 8]
 [1 4 2 6]]


In [34]:
x2_sub = x2[:2, :2]
print (x2_sub)

[[4 1]
 [1 7]]


In [35]:
x2_sub[0, 0] = 99
print (x2_sub)

[[99  1]
 [ 1  7]]


In [36]:
print (x2)

[[99  1  0  6]
 [ 1  7  2  8]
 [ 1  4  2  6]]


Pode parecer estranho, mas isto permite acessar e processar parte dos conjuntos sem a necessidade de copiar o buffer de dados subjacente

Se houver alguma utilidade em criar um cópia explícita dos dados de um array, a forma mais fácil de fazê-lo é o método copy:

In [37]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 1  7]]


Se modificarmos esse subarray, o array original agora não será alterado:

In [38]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  1]
 [ 1  7]]


In [39]:
print(x2)

[[99  1  0  6]
 [ 1  7  2  8]
 [ 1  4  2  6]]
