# Estes são os trechos de código que foram usados nos slides da aula. Ficam aqui para fins de experimentação, caso desejem.

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def calcula_inversos(valores):
    saida = np.empty(len(valores))

    for i in range(len(valores)):
        saida[i] = 1.0 /valores[i]
    return saida

valores = rng.integers(1, 10, size=5)
calcula_inversos(valores)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [ ]:
array_grande = rng.integers(1, 100, size=1000000)
%timeit calcula_inversos(array_grande)

In [ ]:
%timeit (1.0 / array_grande)

In [4]:
#calculando usando a função com loop
print (calcula_inversos(valores))
#calculando usando uma operação vetorizada
print (1.0/ valores)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [5]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)   #NumPy reconhece a função de valor absoluto do Python

array([2, 1, 0, 1, 2])

In [6]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [ ]:
np.abs(x)  #Pode ser np.absolute ou np.abs

array([2, 1, 0, 1, 2])

In [ ]:
angulos = np.linspace(0, np.pi, 3) #0, 90° e 180°
print("ângulos              =", angulos)
print("seno dos ângulos     =", np.sin(angulos))
print("cosseno dos ângulos  =", np.cos(angulos))
print("tangente dos ângulos =", np.tan(angulos))

ângulos              = [0.         1.57079633 3.14159265]
seno dos ângulos     = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosseno dos ângulos  = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tangente dos ângulos = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [7]:
x = [1, 2, 3]
print("x      =", x)
print("e^x    =", np.exp(x))
print("2^x    =", np.exp2(x))
print("3^x    =", np.power(3., x))

x      = [1, 2, 3]
e^x    = [ 2.71828183  7.3890561  20.08553692]
2^x    = [2. 4. 8.]
3^x    = [ 3.  9. 27.]


In [ ]:
x = [1, 2, 4, 10]
print("x         =", x)
print("ln(x)     =", np.log(x))
print("log2(x)   =", np.log2(x))
print("log10(x)  =", np.log10(x))

x         = [1, 2, 4, 10]
ln(x)     = [0.         0.69314718 1.38629436 2.30258509]
log2(x)   = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print (y)

[ 0. 10. 20. 30. 40.]


In [ ]:
y = np.zeros(10)
print(y[::2])
np.power(2, x, out=y[::2])
print(y)

[0. 0. 0. 0. 0.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
